const DEVICE_TYPES={
    IOS:"IOS",
    ANDROID:"ANDROID",
    VR_HEADSET:"VR_HEADSET",
    DESKTOP:"DESKTOP",
    MAC:"MAC",
    LINUX:"LINUX",
}
const STRINGS={
    NOT_AVAILABLE:"NOT_AVAILABLE"
}

const LANGUAGES={
    ENGLISH:"ENGLISH",
    FRENCH:"FRENCH"
}
